//---------------------------------------------------------------
//        Go4 Framework release package V.1.0000
//                      24-May-2002
//---------------------------------------------------------------
//   The GSI Online Offline Object Oriented (Go4) Project
//   Experiment Data Processing at DVEE department, GSI
//---------------------------------------------------------------
//
//Copyright (C) 2000- Gesellschaft f. Schwerionenforschung, GSI
//                    Planckstr. 1, 64291 Darmstadt, Germany
//Contact:            http://go4.gsi.de
//----------------------------------------------------------------
//This software can be used under the license agreements as stated
//in Go4License.txt file which is part of the distribution.
//----------------------------------------------------------------
/* Generated by Together */

#ifndef TEBCALIBRATEFACTORY_H
#define TEBCALIBRATEFACTORY_H
//#include "Go4Event/TGo4EventFactory.h"
//
//#include "Go4Event/TGo4EventElement.h"
//#include "Go4Event/TGo4EventProcessor.h"
//#include "Go4Event/TGo4EventStore.h"
//#include "Go4Event/TGo4EventSource.h"
//#include "Go4Event/TGo4EventProcessorParameter.h"
//#include "Go4Event/TGo4EventStoreParameter.h"
//#include "Go4Event/TGo4EventSourceParameter.h"
//
//#include "Go4EventServer/TGo4FileSource.h"
//#include "Go4EventServer/TGo4FileStore.h"
//#include "Go4EventServer/TGo4TreeSource.h"
//#include "Go4EventServer/TGo4TreeStore.h"


//#include "Go4EventServer/Go4EventServer.h"

#include "TIFJEvent.h"
#include "TIFJCalibratedEvent.h"
#include "TIFJCalibrateProcessor.h"
//#include "Go4EventServer/TGo4EventServerFactory.h"




class TIFJCalibrateFactory   : public TGo4EventServerFactory
{
public:

//      virtual TGo4EventElement * CreateInputEvent();

//      virtual TGo4EventElement * CreateOutputEvent();

//      virtual TGo4EventStore * CreateEventStore(TGo4EventStoreParameter* par);

//      virtual TGo4EventProcessor * CreateEventProcessor(TGo4EventProcessorParameter* par);

    TIFJCalibrateFactory() ;

    TIFJCalibrateFactory(string  name);

    virtual ~TIFJCalibrateFactory() ;

//   private:
//      /**
//      * remember pointer to output event for tree store ctor
//      **/
//      TIFJCalibratedEvent* fxCalibratedEvent; //!

//    ClassDef(TIFJCalibrateFactory,1)
};
#endif //TEBCALIBRATEFACTORY_H
