//---------------------------------------------------------------
//        Go4 Framework release package V.1.0000
//                      24-May-2002
//---------------------------------------------------------------
//   The GSI Online Offline Object Oriented (Go4) Project
//   Experiment Data Processing at DVEE department, GSI
//---------------------------------------------------------------
//
//Copyright (C) 2000- Gesellschaft f. Schwerionenforschung, GSI
//                    Planckstr. 1, 64291 Darmstadt, Germany
//Contact:            http://go4.gsi.de
//----------------------------------------------------------------
//This software can be used under the license agreements as stated
//in Go4License.txt file which is part of the distribution.
//----------------------------------------------------------------
/* Generated by Together */

#ifdef NOGO4


#include "TIFJEventFactory.h"

TIFJEventFactory::TIFJEventFactory(string  name)
    : TGo4EventServerFactory(name)
{

}

TIFJEventFactory::TIFJEventFactory()
    : TGo4EventServerFactory("EB Event Factory")
{

}

TIFJEventFactory::~TIFJEventFactory()
{

}

TGo4EventProcessor * TIFJEventFactory::CreateEventProcessor(TGo4EventProcessorParameter* par)
{

// note: parameter is not yet used here
    TIFJEventProcessor* ebproc = new TIFJEventProcessor;
    /* 14.08.01 EL
    cout << "TIFJEventFactory: creating ebevent processor"<< endl;
    */
    return ebproc;


}

TGo4EventElement * TIFJEventFactory::CreateOutputEvent()
{
    TIFJEvent * ebevent = new TIFJEvent();
//   fxEbEvent = new TIFJEvent();
    /* 14.08.01 EL
    cout << "TIFJEventFactory: creating output event "<< ebevent->ClassName() << endl;
    */
    SetOutputEvent(ebevent); // important for some event store implementations!!!
    return ebevent;


}

ClassImp(TIFJEventFactory)
#endif
